# Generated by Django 5.2.5 on 2025-08-20 08:35

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Destination",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The name of the destination (e.g., Paris, Goa).",
                        max_length=200,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="A captivating description of the destination."
                    ),
                ),
                ("country", models.CharField(max_length=100)),
                (
                    "best_time_to_visit",
                    models.CharField(
                        help_text="e.g., 'October to March'", max_length=100
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        help_text="An attractive image of the destination.",
                        upload_to="destination_images/",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="A unique slug for the destination URL, generated from the name.",
                        unique=True,
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False,
                        help_text="Mark as true to feature this destination on the homepage.",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Enquiry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region=None
                    ),
                ),
                ("message", models.TextField()),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="The date and time the enquiry was submitted.",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Enquiries",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Hotel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The name of the hotel.", max_length=200
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="A detailed description of the hotel."),
                ),
                (
                    "address",
                    models.CharField(
                        help_text="The physical address of the hotel.", max_length=255
                    ),
                ),
                ("city", models.CharField(max_length=100)),
                ("country", models.CharField(max_length=100)),
                (
                    "price_per_night",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Cost for a one-night stay.",
                        max_digits=10,
                    ),
                ),
                (
                    "rating",
                    models.DecimalField(
                        decimal_places=1,
                        help_text="Star rating from 1.0 to 5.0.",
                        max_digits=2,
                    ),
                ),
                (
                    "amenities",
                    models.TextField(
                        help_text="List of amenities, separated by commas (e.g., Wi-Fi, Pool, Gym)."
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        help_text="A representative image of the hotel.",
                        upload_to="hotel_images/",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="A unique slug for the hotel URL, generated from the name.",
                        unique=True,
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False,
                        help_text="Mark as true to feature this hotel on the homepage.",
                    ),
                ),
            ],
        ),
    ]
