# Generated by Django 5.2.5 on 2025-08-20 08:48

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="destination",
            name="description",
            field=ckeditor.fields.RichTextField(
                help_text="A captivating description of the destination, including itinerary and details."
            ),
        ),
        migrations.AlterField(
            model_name="destination",
            name="image",
            field=models.ImageField(
                help_text="The main representative (cover) image of the destination.",
                upload_to="destination_images/",
            ),
        ),
        migrations.AlterField(
            model_name="hotel",
            name="description",
            field=ckeditor.fields.RichTextField(
                help_text="A detailed description of the hotel, including itinerary and details."
            ),
        ),
        migrations.AlterField(
            model_name="hotel",
            name="image",
            field=models.ImageField(
                help_text="The main representative (cover) image of the hotel.",
                upload_to="hotel_images/",
            ),
        ),
        migrations.CreateModel(
            name="DestinationImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="destination_images/gallery/")),
                (
                    "caption",
                    models.CharField(
                        blank=True,
                        help_text="Optional caption for the image.",
                        max_length=200,
                    ),
                ),
                (
                    "destination",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="app.destination",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HotelImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="hotel_images/gallery/")),
                (
                    "caption",
                    models.CharField(
                        blank=True,
                        help_text="Optional caption for the image.",
                        max_length=200,
                    ),
                ),
                (
                    "hotel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="app.hotel",
                    ),
                ),
            ],
        ),
    ]
